with

    base_records as (select * from {{ ref ("base_salesforce__accounts_with_foreign_key_names") }} ), 

    excluding_deleted_records as (select * from base_records where is_deleted = false),

    snake_case_field_names_and_clean_timestamps as (
        -- Original command was using macro and then compiled output shown here for consistency and visibilty of SF Field Aliases
        -- Original command was:   select {% raw %}{{ select_fields_structured(ref('base_salesforce__accounts_with_foreign_key_names')) }}{% endraw %} from excluding_deleted_records
       
select -- Identifiers,

    "ID" as account_id, -- Automatically macro produces different name based on ref. Corrected here.

    
-- Foreign Keys,

    "MASTER_RECORD_ID" as master_record_id,
    "RECORD_TYPE_ID" as record_type_id,
    "PARENT_ID" as parent_id,
    "OWNER_ID" as owner_id,
    "CREATED_BY_ID" as created_by_id,
    "LAST_MODIFIED_BY_ID" as last_modified_by_id,
    "JIGSAW_COMPANY_ID" as jigsaw_company_id,
    "ACTIVITY_METRIC_ID" as activity_metric_id,
    "ACTIVITY_METRIC_ROLLUP_ID" as activity_metric_rollup_id,
    "MIGRATION_ID_C" as migration_id,
    "LANDLORD_ID_C" as landlord_id,
    "OP_ID_C" as op_id,
    "TENANCY_ID_C" as tenancy_id,
    "CASE_THREAD_ID_C" as case_thread_id,
    "VIRGIN_ADDRESS_ID_C" as virgin_address_id,

    
-- Descriptive,

    "NAME" as name,
    "TYPE" as type,
    "INDUSTRY" as industry,
    "DESCRIPTION" as description,

    
-- Dates,

    cast("CREATED_DATE" as timestamp) as created_date,
    cast("LAST_MODIFIED_DATE" as timestamp) as last_modified_date,
    cast("SYSTEM_MODSTAMP" as timestamp) as system_modstamp,
    cast("LAST_ACTIVITY_DATE" as date) as last_activity_date,
    cast("LAST_VIEWED_DATE" as timestamp) as last_viewed_date,
    cast("LAST_REFERENCED_DATE" as timestamp) as last_referenced_date,
    cast("START_DATE_C" as date) as start_date,
    cast("END_DATE_C" as date) as end_date,
    cast("COMMITTED_INSTALL_DATE_C" as date) as committed_install_date,
    cast("AGREEMENT_SIGNED_DATE_1_C" as date) as agreement_signed_date_1,
    cast("AGREEMENT_SIGNED_DATE_2_C" as date) as agreement_signed_date_2,
    cast("FIRST_ENQUIRY_C" as date) as first_enquiry,
    cast("FIRST_ORDER_FORM_DATE_C" as date) as first_order_form_date,
    cast("MID_CONTRACT_INTERNET_UPGRADE_ORDER_DATE_C" as date) as mid_contract_internet_upgrade_order_date,
    cast("CONTRACT_END_DATE_C" as date) as contract_end_date,
    cast("VIRGIN_SERVICEABILITY_SENT_DATE_C" as date) as virgin_serviceability_sent_date,
    cast("AGREEMENT_SENT_DATE_1_C" as date) as agreement_sent_date_1,
    cast("TENANCIES_DISCLAIMER_ACCEPTED_DATE_TIME_C" as timestamp) as tenancies_disclaimer_accepted_date_time,
    cast("X_1_ST_SALES_CALL_C" as date) as x_1_st_sales_call,
    cast("MEETING_DATE_C" as date) as meeting_date,
    cast("WATER_ORDER_DATE_C" as date) as water_order_date,
    cast("AGREEMENT_SENT_DATE_2_C" as date) as agreement_sent_date_2,
    cast("REQUESTED_INSTALLATION_DATE_C" as date) as requested_installation_date,
    cast("ENERGY_ORDER_DATE_C" as date) as energy_order_date,
    cast("INTERNET_ORDER_DATE_C" as date) as internet_order_date,
    cast("WATER_ACCOUNT_NUMBER_DATE_C" as date) as water_account_number_date,
    cast("TV_LICENCE_NUMBER_DATE_C" as date) as tv_licence_number_date,
    cast("TV_LICENCE_ORDER_DATE_C" as date) as tv_licence_order_date,
    cast("DIRECT_DEBIT_CANCELLED_DATE_C" as date) as direct_debit_cancelled_date,
    cast("X_1_ST_INSTALL_DATE_REQUEST_C" as date) as x_1_st_install_date_request,
    cast("TV_LICENCE_START_DATE_C" as date) as tv_licence_start_date,
    cast("X_2_ND_INSTALL_DATE_REQUEST_C" as date) as x_2_nd_install_date_request,
    cast("LATEST_READING_DATE_GAS_C" as date) as latest_reading_date_gas,
    cast("LATEST_READING_DATE_ELEC_C" as date) as latest_reading_date_elec,
    cast("INITIAL_READING_DATE_GAS_C" as date) as initial_reading_date_gas,
    cast("INITIAL_READING_DATE_ELEC_C" as date) as initial_reading_date_elec,
    cast("AGREEMENT_END_DATE_C" as date) as agreement_end_date,
    cast("GAS_SSD_C" as date) as gas_ssd,
    cast("ELECTRICITY_SSD_C" as date) as electricity_ssd,
    cast("GO_LIVE_DATE_2025_C" as date) as go_live_date_2025,
    cast("GO_LIVE_DATE_C" as date) as go_live_date,
    cast("DATE_WON_C" as date) as date_won,
    cast("CANCELLATION_DATE_C" as date) as cancellation_date,
    cast("DATE_ACCOUNT_COMPLETED_C" as date) as date_account_completed,
    cast("SEWERAGE_ORDER_DATE_C" as date) as sewerage_order_date,
    cast("PREPAYMENT_METER_EXCHANGE_DATE_C" as date) as prepayment_meter_exchange_date,
    cast("PROOF_OF_UTILITY_PAYMENTS_DATE_C" as date) as proof_of_utility_payments_date,
    cast("GAS_LAST_REAPPLY_DATE_C" as date) as gas_last_reapply_date,
    cast("ELECTRIC_LAST_REAPPLY_DATE_C" as date) as electric_last_reapply_date,
    cast("GO_LIVE_DATE_22_23_C" as date) as go_live_date_22_23,
    cast("ROUTER_DELIVERY_DATE_C" as date) as router_delivery_date,
    cast("AGREEMENT_END_DATE_2_C" as date) as agreement_end_date_2,
    cast("PAUSE_START_DATE_C" as date) as pause_start_date,
    cast("PAUSE_END_DATE_C" as date) as pause_end_date,
    cast("DATE_OF_LAST_ENQUIRY_C" as date) as date_of_last_enquiry,
    cast("ESTIMATED_ROUTER_DELIVER_DATE_C" as date) as estimated_router_deliver_date,
    cast("LAST_FORM_DATE_C" as date) as last_form_date,
    cast("OCR_FIRST_SIGNED_DATE_C" as date) as ocr_first_signed_date,
    cast("OCR_LAST_SIGNED_DATE_C" as date) as ocr_last_signed_date,
    cast("DATE_CLOSED_C" as date) as date_closed,
    cast("LAST_VERBAL_ACTIVITY_BY_ACCOUNT_OWNER_C" as timestamp) as last_verbal_activity_by_account_owner,
    cast("LAST_WRITTEN_ACTIVITY_BY_ACCOUNT_OWNER_C" as timestamp) as last_written_activity_by_account_owner,
    cast("COMPANY_CREATION_DATE_C" as date) as company_creation_date,
    cast("GAS_ORDER_DATE_C" as date) as gas_order_date,
    cast("LAST_UTILITY_STATUS_UPDATE_C" as date) as last_utility_status_update,
    cast("ACTIVE_DATE_C" as date) as active_date,
    cast("EXTENSION_DATE_PRICE_INCREASE_C" as date) as extension_date_price_increase,
    cast("READING_DATE_ELEC_2_C" as date) as reading_date_elec_2,
    cast("CAMPAIGN_TARGET_SEND_DATE_C" as date) as campaign_target_send_date,
    cast("CAMPAIGN_SEND_DATE_C" as date) as campaign_send_date,
    cast("SERVICE_UPDATE_C" as date) as service_update,
    cast("METER_READINGS_REQUEST_C" as date) as meter_readings_request,
    cast("ELECTRICITY_ORDER_DATE_C" as date) as electricity_order_date,
    cast("X_23_24_GO_LIVE_DATE_C" as date) as x_23_24_go_live_date,
    cast("DATE_INTERNET_UPGRADE_EMAIL_SENT_C" as timestamp) as date_internet_upgrade_email_sent,
    cast("DATE_TIME_INTERNET_PACKAGE_SELECTED_C" as timestamp) as date_time_internet_package_selected,
    cast("FIBRE_SERVICEABILITY_SENT_DATE_C" as date) as fibre_serviceability_sent_date,
    cast("TENANT_MOVE_IN_C" as date) as tenant_move_in,
    cast("ROUTER_REPLACEMENT_DATE_C" as date) as router_replacement_date,
    cast("X_24_25_GO_LIVE_DATE_C" as date) as x_24_25_go_live_date,
    cast("UNIFIED_ACTIVE_DATE_C" as date) as unified_active_date,
    cast("GAS_ACCOUNT_CLOSED_DATE_C" as date) as gas_account_closed_date,
    cast("EPC_VALID_UNTIL_C" as date) as epc_valid_until,
    cast("ELECTRICITY_ACCOUNT_CLOSED_DATE_C" as date) as electricity_account_closed_date,
    cast("_FIVETRAN_SYNCED" as timestamp) as fivetran_synced,
    cast("LAST_SUCCESSFUL_VERBAL_ACTIVITY_C" as timestamp) as last_successful_verbal_activity,

    
-- Measures,

    "TOTAL_CONTRACT_VALUE_C" as total_contract_value,

    
-- Other Fields,

    "IS_DELETED" as is_deleted,
    "BILLING_STREET" as billing_street,
    "BILLING_CITY" as billing_city,
    "BILLING_STATE" as billing_state,
    "BILLING_POSTAL_CODE" as billing_postal_code,
    "BILLING_COUNTRY" as billing_country,
    "BILLING_LATITUDE" as billing_latitude,
    "BILLING_LONGITUDE" as billing_longitude,
    "BILLING_GEOCODE_ACCURACY" as billing_geocode_accuracy,
    "SHIPPING_STREET" as shipping_street,
    "SHIPPING_CITY" as shipping_city,
    "SHIPPING_STATE" as shipping_state,
    "SHIPPING_POSTAL_CODE" as shipping_postal_code,
    "SHIPPING_COUNTRY" as shipping_country,
    "SHIPPING_LATITUDE" as shipping_latitude,
    "SHIPPING_LONGITUDE" as shipping_longitude,
    "SHIPPING_GEOCODE_ACCURACY" as shipping_geocode_accuracy,
    "PHONE" as phone,
    "FAX" as fax,
    --"ACCOUNT_NUMBER" as account_number_0,
    "WEBSITE" as website,
    "PHOTO_URL" as photo_url,
    "SIC" as sic,
    "ANNUAL_REVENUE" as annual_revenue,
    "NUMBER_OF_EMPLOYEES" as number_of_employees,
    "OWNERSHIP" as ownership,
    "TICKER_SYMBOL" as ticker_symbol,
    "RATING" as rating,
    "SITE" as site,
    "IS_PARTNER" as is_partner,
    "IS_CUSTOMER_PORTAL" as is_customer_portal,
    "CHANNEL_PROGRAM_NAME" as channel_program_name,
    "CHANNEL_PROGRAM_LEVEL_NAME" as channel_program_level_name,
    "JIGSAW" as jigsaw,
    "ACCOUNT_SOURCE" as account_source,
    "SIC_DESC" as sic_desc,
    "IS_PRIORITY_RECORD" as is_priority_record,
    "SUPPLYING_NEXT_YEAR_C" as supplying_next_year,
    "GAS_METER_TYPE_C" as gas_meter_type,
    "BILLS_INCLUDED_C" as bills_included,
    "SOURCE_C" as source,
    "PORTFOLIO_SIZE_C" as portfolio_size,
    "GAS_C" as gas,
    "ELECTRICITY_C" as electricity,
    "WATER_C" as water,
    "CURRENTLY_INSTALLED_INTERNET_C" as currently_installed_internet,
    "WEEKLY_COST_C" as weekly_cost,
    "TV_LICENCE_C" as tv_licence,
    "ENERGY_ACCOUNT_NUMBER_C" as energy_account_number,
    "CONTRACT_VERSION_C" as contract_version,
    "WATER_ACCOUNT_NUMBER_C" as water_account_number,
    "TV_LICENCE_NUMBER_C" as tv_licence_number,
    "WATER_TYPE_C" as water_type,
    "SUPPLIER_TYPE_C" as supplier_type,
    "ACCOUNT_TYPE_C" as account_type,
    "CLOSEST_UNIVERSITY_C" as closest_university,
    "GAS_SUPPLIER_C" as gas_supplier,
    "INTERNET_PACKAGE_C" as internet_package,
    "WATER_SUPPLIER_C" as water_supplier,
    "CONTACTS_WITHOUT_A_DD_C" as contacts_without_a_dd,
    "EMAIL_ADDRESS_C" as email_address,
    "INTERNET_ACCOUNT_NUMBER_C" as internet_account_number,
    "GROUP_SIZE_C" as group_size,
    "PROPERTY_SIZE_C" as property_size,
    "PARTNERSHIP_BADGE_C" as partnership_badge,
    "SALES_INCENTIVE_C" as sales_incentive,
    "FIBRE_AVAILABLE_C" as fibre_available,
    "GAS_METER_C" as gas_meter,
    "INSTALL_SLOT_C" as install_slot,
    "ROUTER_MAC_ADDRESS_C" as router_mac_address,
    "ELECTRICITY_METER_TYPE_C" as electricity_meter_type,
    "PREVIOUS_ELECTRICITY_SUPPLIER_C" as previous_electricity_supplier,
    "PREVIOUS_GAS_SUPPLIER_C" as previous_gas_supplier,
    "ESTIMATED_ANNUAL_GAS_USAGE_C" as estimated_annual_gas_usage,
    "ESTIMATED_ANNUAL_ELECTRICITY_USAGE_C" as estimated_annual_electricity_usage,
    "ACCOUNT_MANAGER_C" as account_manager,
    "NUMBER_OF_CONTACTS_C" as number_of_contacts,
    "TV_LICENCE_CLOSED_C" as tv_licence_closed,
    "ONLINE_SETUP_C" as online_setup,
    "STATUS_C" as status,
    "ACCOUNT_NUMBER_C" as account_number,
    "ENQUIRY_SOURCE_C" as enquiry_source,
    "WATER_STATUS_C" as water_status,
    "MPAN_C" as mpan,
    "LANDLORD_AGENT_NAME_C" as landlord_agent_name,
    "NUMBER_OF_DD_SIGNUPS_C" as number_of_dd_signups,
    "ELECTRIC_METER_C" as electric_meter,
    "SEWERAGE_WATER_STATUS_C" as sewerage_water_status,
    "STOP_FUTURE_PAYMENTS_C" as stop_future_payments,
    "ELECTRICITY_REGION_C" as electricity_region,
    "PREDICTED_METER_USAGE_AQ_C" as predicted_meter_usage_aq,
    "INSTALL_TYPE_C" as install_type,
    "VIRGIN_AVAILABLE_C" as virgin_available,
    "ROUTE_C" as route,
    "MPRN_C" as mprn,
    "VIRGIN_SERVICEABILITY_SENT_C" as virgin_serviceability_sent,
    "PRIMARY_CONTACT_NAME_C" as primary_contact_name,
    "PRIMARY_CONTACT_NUMBER_C" as primary_contact_number,
    "RECEIVED_CLOSING_READINGS_C" as received_closing_readings,
    "RECEIVED_OPENING_READINGS_C" as received_opening_readings,
    "LANDLORD_AGENT_REFERRAL_C" as landlord_agent_referral,
    "SUPPLY_DATA_COPIED_FROM_PREVIOUS_YEAR_C" as supply_data_copied_from_previous_year,
    "CO_T_EMAIL_ADDRESS_C" as co_t_email_address,
    "HOME_MOVE_PHONE_C" as home_move_phone,
    "AGENT_TYPE_PBSA_BTR_C" as agent_type_pbsa_btr,
    "DIRECT_DEBIT_CANCELLED_C" as direct_debit_cancelled,
    "CROSS_SELL_ABILITY_YES_NO_C" as cross_sell_ability_yes_no,
    "PAYMENT_DOCUMENT_TO_BE_GENERATED_C" as payment_document_to_be_generated,
    "CUSTOMER_WARNING_C" as customer_warning,
    "SUPPLIED_LAST_YEAR_C" as supplied_last_year,
    "TOTAL_COLLECTED_PAYMENTS_C" as total_collected_payments,
    "USERNAME_C" as username,
    "TEMP_EMAIL_SEND_FLAG_C" as temp_email_send_flag,
    "INSTALL_DATE_SENT_C" as install_date_sent,
    "PORTFOLIO_NOTES_C" as portfolio_notes,
    "LATEST_READING_GAS_K_WH_C" as latest_reading_gas_k_wh,
    "LATEST_READING_ELEC_K_WH_C" as latest_reading_elec_k_wh,
    "INITIAL_READING_GAS_C" as initial_reading_gas,
    "INITIAL_READING_ELEC_C" as initial_reading_elec,
    "VOUCHER_CODE_USED_C" as voucher_code_used,
    "INCUMBENT_GAS_SUPPLIER_C" as incumbent_gas_supplier,
    "SUPPLY_INFO_MIGRATED_FLAG_C" as supply_info_migrated_flag,
    "ENERGY_PROMOTION_OPT_IN_C" as energy_promotion_opt_in,
    "BILLING_TYPE_C" as billing_type,
    "AGREEMENT_STATUS_C" as agreement_status,
    "FORMS_C" as forms,
    "PDF_S_C" as pdf_s,
    "LISTINGS_C" as listings,
    "GO_LIVE_CALL_C" as go_live_call,
    "GAS_STATUS_C" as gas_status,
    "ELECTRICITY_STATUS_C" as electricity_status,
    "TENANCY_SIGN_UP_PROCESS_C" as tenancy_sign_up_process,
    "AGREEMENT_TYPE_C" as agreement_type,
    "UTILITY_FORM_SIGN_UP_PROCESS_C" as utility_form_sign_up_process,
    "ENERGY_ACCOUNT_CLOSED_C" as energy_account_closed,
    "WATER_CLOSED_C" as water_closed,
    "INTERNET_CLOSED_C" as internet_closed,
    "INITIAL_GAS_READING_C" as initial_gas_reading,
    "LATEST_GAS_READING_C" as latest_gas_reading,
    "REFERRAL_FEE_PAID_C" as referral_fee_paid,
    "RE_SIGN_INFO_C" as re_sign_info,
    "PAYMENT_METHOD_LANDLORD_AGENT_C" as payment_method_landlord_agent,
    "ORDER_TYPE_C" as order_type,
    "GAS_SERIAL_NUMBER_C" as gas_serial_number,
    "ELECTRICITY_SERIAL_NUMBER_C" as electricity_serial_number,
    "GAS_ACCOUNT_NUMBER_C" as gas_account_number,
    "ELECTRICITY_ACCOUNT_NUMBER_C" as electricity_account_number,
    "INCUMBENT_ELECTRICITY_SUPPLIER_C" as incumbent_electricity_supplier,
    "METER_READ_URL_OVERRIDE_C" as meter_read_url_override,
    "GET_GREEN_ENERGY_DATA_C" as get_green_energy_data,
    "SUPPLIER_CODE_GAS_C" as supplier_code_gas,
    "HOUSEMATE_JOIN_LINK_C" as housemate_join_link,
    "LOST_REASON_C" as lost_reason,
    "ENERGY_WEEKLY_COST_PP_C" as energy_weekly_cost_pp,
    "BROADBAND_WEEKLY_COST_PP_C" as broadband_weekly_cost_pp,
    "WATER_WEEKLY_COST_PP_C" as water_weekly_cost_pp,
    "TV_LICENCE_WEEKLY_COST_PP_C" as tv_licence_weekly_cost_pp,
    "ENERGY_SUPPLIER_C" as energy_supplier,
    "GET_LAST_YEAR_S_DATA_C" as get_last_year_s_data,
    "COMPANY_REGISTRATION_NUMBER_C" as company_registration_number,
    "INTERNET_PROVIDER_C" as internet_provider,
    "DO_AUTO_SIGNUP_INTERNET_PACKAGE_C" as do_auto_signup_internet_package,
    "SEND_INTERNET_SELECTION_EMAIL_C" as send_internet_selection_email,
    "CAMPAIGN_SOURCE_C" as campaign_source,
    "SEND_INTERNET_UPGRADE_EMAIL_C" as send_internet_upgrade_email,
    "UTILITY_E_SHOT_C" as utility_e_shot,
    "SEWERAGE_SUPPLIER_C" as sewerage_supplier,
    "TENANT_TYPE_C" as tenant_type,
    "INITIAL_ELECTRICITY_READING_2_K_WH_C" as initial_electricity_reading_2_k_wh,
    "QUEUE_METER_READ_EMAIL_C" as queue_meter_read_email,
    "SEWERAGE_ACCOUNT_NUMBER_C" as sewerage_account_number,
    "ROUTER_TRACKING_NUMBER_C" as router_tracking_number,
    "ROUTER_TRACKING_SENT_C" as router_tracking_sent,
    "ACCOUNT_PAID_IN_FULL_C" as account_paid_in_full,
    "SEND_OPENING_METER_READING_EMAIL_C" as send_opening_meter_reading_email,
    "SEND_INTERNET_SUPPORT_EMAIL_C" as send_internet_support_email,
    "TRUSTPILOT_REVIEW_C" as trustpilot_review,
    "GOOGLE_REVIEW_C" as google_review,
    "SUPPLIER_PARTNER_ACCOUNT_C" as supplier_partner_account,
    "AGENT_BILLING_PAYMENT_DATES_C" as agent_billing_payment_dates,
    "EPC_HABITABLE_ROOMS_C" as epc_habitable_rooms,
    "EPC_HEATED_ROOMS_C" as epc_heated_rooms,
    "EPC_MAIN_FUEL_C" as epc_main_fuel,
    "EPC_MAIN_HEAT_FEATURE_DESCRIPTION_C" as epc_main_heat_feature_description,
    "REALISTIC_SHARER_PORTFOLIO_C" as realistic_sharer_portfolio,
    "EPC_MAINS_GAS_C" as epc_mains_gas,
    "EPC_POTENTIAL_RATING_C" as epc_potential_rating,
    "EPC_PROPERTY_TYPE_C" as epc_property_type,
    "EPC_RATING_C" as epc_rating,
    "EPC_TOTAL_FLOOR_AREA_C" as epc_total_floor_area,
    "REALISTIC_STUDENT_PORTFOLIO_C" as realistic_student_portfolio,
    "TOTAL_SHARER_PORTFOLIO_C" as total_sharer_portfolio,
    "EPC_WINDOW_FEATURE_DESCRIPTION_C" as epc_window_feature_description,
    "FIBRE_AVAILABILITY_C" as fibre_availability,
    "AGREEMENT_STATUS_2_C" as agreement_status_2,
    "AGREEMENT_TYPE_2_C" as agreement_type_2,
    "LOST_SUPPLIER_C" as lost_supplier,
    "LIST_OF_CONTACTS_C" as list_of_contacts,
    "COMMISSION_DEDUCTION_C" as commission_deduction,
    "BITLY_ERROR_MESSAGE_MR_C" as bitly_error_message_mr,
    "CLOSED_REASON_C" as closed_reason,
    "PAUSE_REASON_C" as pause_reason,
    "WORD_ORDER_FORMS_SENT_C" as word_order_forms_sent,
    "FORM_UPDATE_REPORT_CREATED_C" as form_update_report_created,
    "PRICE_VERIFIED_C" as price_verified,
    "E_GIFT_APPLICABLE_C" as e_gift_applicable,
    "EPC_CHECKED_DEV_ONLY_C" as epc_checked_dev_only,
    "AGENT_BILLING_PAYMENT_TERMS_C" as agent_billing_payment_terms,
    "INCLUDE_VAT_C" as include_vat,
    "ENQUIRIES_SINCE_LAST_FORM_DATE_C" as enquiries_since_last_form_date,
    "MAXIMUM_DOWNLOAD_SPEED_MB_C" as maximum_download_speed_mb,
    "DEPOSIT_PROTECTION_SCHEME_C" as deposit_protection_scheme,
    "PROVIDER_TYPE_C" as provider_type,
    "OCTOBER_ELECTRICITY_READ_RECEIVED_C" as october_electricity_read_received,
    "OCTOBER_GAS_READ_RECEIVED_C" as october_gas_read_received,
    "EXPECTED_NUMBER_OF_PROPERTIES_C" as expected_number_of_properties,
    "WELCOME_EMAIL_C" as welcome_email,
    "TEAM_C" as team,
    "BITLY_INTERNET_INSTALL_DATE_URL_C" as bitly_internet_install_date_url,
    "RUN_PRICE_VALIDATION_C" as run_price_validation,
    "LEAD_SOURCE_C" as lead_source,
    "USES_UTILITY_CONNECT_C" as uses_utility_connect,
    "OF_PORTFOLIO_LET_C" as of_portfolio_let,
    "MOBILE_PROVIDER_C" as mobile_provider,
    "TOTAL_ORDER_FORMS_C" as total_order_forms,
    "OCR_NAME_C" as ocr_name,
    "OCR_EMAIL_C" as ocr_email,
    "FORM_AMENDMENTS_C" as form_amendments,
    "FILE_DETAILS_FOR_OCR_C" as file_details_for_ocr,
    "OCR_FILE_RETRIEVED_C" as ocr_file_retrieved,
    "BITLY_RESPONSE_MR_C" as bitly_response_mr,
    "HAPPY_TO_RECOMMEND_C" as happy_to_recommend,
    "GAS_ACCOUNT_CLOSED_C" as gas_account_closed,
    "ASSOCIATED_CITY_C" as associated_city,
    "TRIGGER_SUPPLIED_LAST_YEAR_MANUALLY_C" as trigger_supplied_last_year_manually,
    "STB_ORDER_FORM_C" as stb_order_form,
    "COMPANY_HOUSE_STATUS_C" as company_house_status,
    "MULTI_MPAN_C" as multi_mpan,
    "PROPOSED_ELECTRICITY_SUPPLIER_C" as proposed_electricity_supplier,
    "PROPOSED_EL_SUPPLIER_ACCOUNT_NUMBER_C" as proposed_el_supplier_account_number,
    "MINIMUM_DOWNLOAD_SPEED_MB_C" as minimum_download_speed_mb,
    "REGISTERED_COMPANY_NAME_C" as registered_company_name,
    "MULTI_MPRN_C" as multi_mprn,
    "PROPOSED_GAS_SUPPLIER_C" as proposed_gas_supplier,
    "PROPOSED_GAS_SUPPLIER_ACCOUNT_NUMBER_C" as proposed_gas_supplier_account_number,
    "VIRGIN_CONSTRUCTION_ORDER_SENT_C" as virgin_construction_order_sent,
    "NUMBER_OF_MAIN_CONTACTS_C" as number_of_main_contacts,
    "SEND_AGREEMENT_TO_C" as send_agreement_to,
    "ALLOWED_PROPERTY_LIMIT_C" as allowed_property_limit,
    "ALLOW_BROADBAND_DISCOUNT_C" as allow_broadband_discount,
    "RATEABLE_VALUE_NUMBER_C" as rateable_value_number,
    "CROSS_SELL_ATTEMPTED_C" as cross_sell_attempted,
    "TOTAL_STUDENT_PORTFOLIO_C" as total_student_portfolio,
    "PAID_C" as paid,
    "UTILITIES_ALREADY_INCLUDED_C" as utilities_already_included,
    "ELECTRICITY_PPM_MODE_C" as electricity_ppm_mode,
    "GAS_PPM_MODE_C" as gas_ppm_mode,
    "ENERGY_PROFILE_C" as energy_profile,
    "RECOMMENDATION_NOTES_C" as recommendation_notes,
    "NEW_AB_AGREEMENT_STATUS_PRICE_INCREASE_C" as new_ab_agreement_status_price_increase,
    "COMMISSION_C" as commission,
    "NEW_FORMS_SENT_PRICE_INCREASE_C" as new_forms_sent_price_increase,
    "NEW_MARKETING_MATERIALS_SENT_PRICE_INCR_C" as new_marketing_materials_sent_price_incr,
    "CALL_STATUS_PRICE_INCREASE_C" as call_status_price_increase,
    "LENGTH_C" as length,
    "READING_ELEC_2_C" as reading_elec_2,
    "PARENT_COMPANY_C" as parent_company,
    "EXCLUDE_FROM_COMMISSION_AUTOMATION_C" as exclude_from_commission_automation,
    "NUMBER_C" as number,
    "EXCLUDE_FROM_COMMISSIONS_C" as exclude_from_commissions,
    "OPT_OUT_METER_READING_AUTOMATION_C" as opt_out_meter_reading_automation,
    "INTERNET_UTILITY_STATUS_C" as internet_utility_status,
    "GAS_UTILITY_STATUS_C" as gas_utility_status,
    "WATER_UTILITY_STATUS_C" as water_utility_status,
    "ELECTRICITY_UTILITY_STATUS_C" as electricity_utility_status,
    "TV_LICENCE_UTILITY_STATUS_C" as tv_licence_utility_status,
    "CAMPAIGN_LAUNCH_CALL_C" as campaign_launch_call,
    "RENT_ONLY_PROPERTIES_LET_C" as rent_only_properties_let,
    "METHOD_C" as method,
    "CAMPAIGN_SEND_DATE_CALL_STATUS_C" as campaign_send_date_call_status,
    "RESULTS_C" as results,
    "UTILITY_CROSS_SELL_CAMPAIGN_CODE_C" as utility_cross_sell_campaign_code,
    "GAS_SMART_METER_ACTIVE_C" as gas_smart_meter_active,
    "ELECTRICITY_SMART_METER_ACTIVE_C" as electricity_smart_meter_active,
    "VIRGIN_CAT_NUMBER_C" as virgin_cat_number,
    "SHORT_METER_READ_LINK_C" as short_meter_read_link,
    "OTHER_REASON_LOST_C" as other_reason_lost,
    "MPAN_2_C" as mpan_2,
    "MPRN_2_C" as mprn_2,
    "COMMUNITY_HEATING_C" as community_heating,
    "PAYMENT_INFORMATION_EMAIL_C" as payment_information_email,
    "DUPLICATE_CONTACTS_C" as duplicate_contacts,
    "LATEST_ELECTRICITY_SKIPPED_REASON_C" as latest_electricity_skipped_reason,
    "LATEST_GAS_SKIPPED_REASON_C" as latest_gas_skipped_reason,
    "NUMBER_OF_BUILDINGS_C" as number_of_buildings,
    "REFRESH_PROPERTY_LINK_C" as refresh_property_link,
    "EPC_MANUAL_CHECK_C" as epc_manual_check,
    "ENERGY_REMOVAL_REASON_C" as energy_removal_reason,
    "ENERGY_WEEKLY_COST_DEDUCTED_PP_C" as energy_weekly_cost_deducted_pp,
    "NUMBER_OF_UNITS_C" as number_of_units,
    "ENERGY_FOLLOW_UP_CALL_C" as energy_follow_up_call,
    "PRICE_PER_WEEK_C" as price_per_week,
    "WHICH_UTILITIES_ARE_ALREADY_INCLUDED_C" as which_utilities_are_already_included,
    "HIGH_PRIORITY_C" as high_priority,
    "EXCLUDE_FROM_22_23_COMMISSION_C" as exclude_from_22_23_commission,
    "OCCUPANCY_TURNOVER_PER_ANNUAL_C" as occupancy_turnover_per_annual,
    "MARKETING_SOURCE_ACCOUNT_C" as marketing_source_account,
    "EST_UNIT_NUMBER_C" as est_unit_number,
    "PHYSICAL_ORDER_FORMS_C" as physical_order_forms,
    "OPERATION_METHOD_C" as operation_method,
    "INCUMBENT_ELECTRICITY_ACCOUNT_NUMBER_C" as incumbent_electricity_account_number,
    "INCUMBENT_GAS_ACCOUNT_NUMBER_C" as incumbent_gas_account_number,
    "REGISTERED_STREET_C" as registered_street,
    "REGISTERED_CITY_C" as registered_city,
    "REGISTERED_REGION_C" as registered_region,
    "REGISTERED_COUNTRY_C" as registered_country,
    "REGISTERED_POSTCODE_C" as registered_postcode,
    "ENERGY_TARIFF_C" as energy_tariff,
    "SUPPLIER_CODE_ELECTRICITY_C" as supplier_code_electricity,
    "PRIMARY_CONTACT_EMAIL_C" as primary_contact_email,
    "INTERNET_PACKAGE_CONFIRMED_C" as internet_package_confirmed,
    "INTERNET_UPGRADED_BY_NAME_C" as internet_upgraded_by_name,
    "WEEKLY_INTERNET_UPGRADE_COST_C" as weekly_internet_upgrade_cost,
    "NEW_ADDRESS_C" as new_address,
    "GAS_BUSINESS_SUPPLIER_C" as gas_business_supplier,
    "ELECTRICITY_BUSINESS_SUPPLIER_C" as electricity_business_supplier,
    "TENANT_MOVE_IN_NAME_C" as tenant_move_in_name,
    "DASHBOARD_WALKTHROUGH_C" as dashboard_walkthrough,
    "CONTRACT_VERSION_1_C" as contract_version_1,
    "CONTRACT_VERSION_2_C" as contract_version_2,
    "EXCLUDE_FROM_INSTALLATION_AUTOMATION_C" as exclude_from_installation_automation,
    "EXCLUDE_INTERNET_EMAILS_C" as exclude_internet_emails,
    "RESET_SUPPLIED_LAST_YEAR_DEV_ONLY_C" as reset_supplied_last_year_dev_only,
    "USING_E_SIGN_C" as using_e_sign,
    "STOP_ELECTRICITY_API_C" as stop_electricity_api,
    "SAGE_CUSTOMER_NUMBER_COUNTER_C" as sage_customer_number_counter,
    "VIRGIN_REPLACEMENT_ROUTER_TEMPORARY_FLAG_C" as virgin_replacement_router_temporary_flag,
    "HOWDENS_CLIENT_C" as howdens_client,
    "NO_DIRECT_DEBIT_EMAIL_SENT_C" as no_direct_debit_email_sent,
    "BUSINESS_SUPPLIER_FLAG_C" as business_supplier_flag,
    "GAS_METER_BRAND_C" as gas_meter_brand,
    "GAS_METER_LOCATION_C" as gas_meter_location,
    "STOP_GAS_API_C" as stop_gas_api,
    "MARKETING_QUALIFIED_C" as marketing_qualified,
    "FTTP_AVAILABLE_C" as fttp_available,
    "WATER_RENEWAL_CHECK_C" as water_renewal_check,
    "CONTRACT_AMENDMENTS_1_C" as contract_amendments_1,
    "CONTRACT_AMENDMENTS_2_C" as contract_amendments_2,
    "BOOSTS_REMAINING_C" as boosts_remaining,
    "ELEC_EXPECTED_USAGE_TO_DATE_C" as elec_expected_usage_to_date,
    "ELEC_USAGE_SINCE_INITIAL_READING_C" as elec_usage_since_initial_reading,
    "GAS_EXPECTED_USAGE_TO_DATE_C" as gas_expected_usage_to_date,
    "GAS_USAGE_SINCE_INITIAL_READING_C" as gas_usage_since_initial_reading,
    "HOW_DID_YOU_HEAR_ABOUT_US_C" as how_did_you_hear_about_us,
    "LEAD_TYPE_C" as lead_type,
    "INTERNAL_BROADBAND_UPGRADE_USER_C" as internal_broadband_upgrade_user,
    "PROPERTY_C" as property,
    "_FIVETRAN_DELETED" as fivetran_deleted,
    "TV_LICENSE_CLOSED_BY_BATCH_C" as tv_license_closed_by_batch,
    "TV_LICENSE_ORDERED_BY_BATCH_C" as tv_license_ordered_by_batch,
    "WATER_CLOSED_BY_BATCH_C" as water_closed_by_batch,
    "WATER_ORDERED_BY_BATCH_C" as water_ordered_by_batch,
    "TARIFF_C" as tariff,
    "ELECTRICITY_ONLY_C" as electricity_only,
    "STUDENT_BILLING_PRICE_PPW_C" as student_billing_price_ppw,
    "RECORD_TYPE_NAME" as record_type_name,
    "OWNER_NAME" as owner_name,
    "CREATED_BY_NAME" as created_by_name,
    "LAST_MODIFIED_BY_NAME" as last_modified_by_name,
    "PARENT_ACCOUNT_NAME" as parent_account_name from excluding_deleted_records

    )

select *
from snake_case_field_names_and_clean_timestamps
